import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import ReactQueryProvider from "@/query/ReactQueryProvider";
import { ContextProvider } from "@/context/Context";
import Head from "next/head";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Green Shop",
  description: "Generated by create next app",
  icons: {
    shortcut: "/images/site-favicon.svg",
  },
};
  
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ReactQueryProvider>
            <ContextProvider>
              <Header/>
              {children}
            </ContextProvider>
          </ReactQueryProvider>
        </body>
    </html>
  );
}
